config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  resources :questions, shallow: true, concerns: :votable do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    member do
      patch :subscribe
      delete :unsubscribe
    end
    resources :answers, only: [:create, :destroy, :update], concerns: :votable do
      resources :comments, only: [:create], defaults: { commentable: 'answers' }
      member do
        patch 'best'
      end
    end
  end

  resources :attachments, only: [:destroy]

  root 'questions#index'
  get '/search', to: 'searches#search'
  get '/terms', to: redirect('/terms.html')
  get '/privacy', to: redirect('/privacy.html')

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, shallow: true, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :attachments, dependent: :destroy, as: :attachable, inverse_of: :attachable
  belongs_to :user
  has_many :subscribers, through: :subscriptions, source: 'user', foreign_key: 'user_id'

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5, maximum: 150 }
  validates :body, length: { maximum: 3000 }
  validates :user_id, presence: true

  accepts_nested_attributes_for :attachments, allow_destroy: true

  scope :last24h, -> do
    Question.where(created_at: (Time.zone.now.midnight - 1.day)..Time.zone.now.midnight)
  end

  default_scope { order(created_at: 'ASC') }

  after_create :subscribe_author

  def subscribe(user)
    subscriptions.create!(user: user)
  end

  def unsubscribe(user)
    Subscription.find_by(user: user).destroy
  end

  private

  def subscribe_author
    subscribe(user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user: current_resource_owner)))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_question, only: [:show, :destroy, :update, :subscribe, :unsubscribe]
  before_action :load_answers, only: :show
  after_action :publish_question, only: :create

  respond_to :js

  authorize_resource

  def new
    respond_with(@question = Question.new)
  end

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with(@question)
  end

  def create
    respond_with(@question = Question.create(question_params.merge(user: current_user)))
  end

  def update
    return unless current_user.author_of?(@question)
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    current_user.author_of?(@question) ? respond_with(@question.destroy) : redirect_to(@question)
  end

  def subscribe
    @question.subscribe(current_user)
  end

  def unsubscribe
    @question.unsubscribe(current_user)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def load_answers
    @answers = @question.answers
  end

  def publish_question
    PrivatePub.publish_to "/questions", question: @question.to_json if @question.valid?
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
  .nested-fields
    .field
      .form-group
        = f.label :file, 'Attach a file:'
        = f.file_field :file
    = link_to_remove_association "Hide the form", f
    br
    hr

app/views/questions/_attachments.html.slim
i Attachments:
p
#attachments
  .links
    = link_to_add_association 'Add a file', f, :attachments
  = f.fields_for :attachments do |a|
    = render 'attachment_fields', f: a
    
br
br
= f.submit "Save", class: "btn btn-sm btn-primary"

app/views/questions/_question.html.slim
  .subscription
    - if can?(:subscribe, @question) || can?(:unsubscribe, @question)
      |Subscription to new answers:
      span.subscribed-info style=('display:none' unless can?(:unsubscribe, @question))
        strong< subscribed!
      span.subscribe-button style=('display:none' unless can?(:subscribe, @question))
        =< link_to('Subscribe', subscribe_question_path(@question), method: :patch, 
          class: 'btn btn-xs btn-info', id: 'create-subscription', remote: true)
      span.unsubscribe-button style=('display:none' unless can?(:unsubscribe, @question))
        =< link_to('Unsubscribe', unsubscribe_question_path(@question), method: :delete, 
          class: 'btn btn-xs btn-warning', id: 'delete-subscription', remote: true)
  h3
    = @question.title
  hr
  .row
    .col-md-1.question-rating
      .question-votes
        - if can?(:vote_up, @question)
          .vote-button-up style=('display:none' unless can?(:vote_up, @question))
            =link_to('',vote_up_question_path, method: :patch, class: 'fa fa-sort-asc', 
              id: 'q-vote-up', remote: true, data: { type: :json })
        span.q-rating =@question.votes_sum
        - if can?(:vote_down, @question) || can?(:cancel_vote, @question)
          .cancel-vote style=('display:none' unless can?(:cancel_vote, @question))
            br
            =link_to('',cancel_vote_question_path, method: :delete, class: 'fa fa-times',
              id: 'q-cancel-vote', remote: true, data: { type: :json })
        - if can?(:vote_down, @question)
          .vote-button-down style=('display:none' unless can?(:vote_down, @question))
            =link_to('',vote_down_question_path, method: :patch, class: 'fa fa-sort-desc',
              id: 'q-vote-down', remote: true, data: { type: :json })
    .col-md-11
      p
        = @question.body

      - if @question.attachments.any?
        strong 
          em Attachments:
        ul
          - @question.attachments.each do |a|
            li id="file-#{a.id}"
              = link_to(a.file.identifier, a.file.url)
              |&nbsp;&nbsp;&nbsp;
              = link_to('delete', a, method: :delete, id: "delete-file-#{a.id}", class: 'btn btn-xs btn-danger', 
                remote: true) if can?(:destroy, a) 

      - if can?(:update, @question) && can?(:destroy, @question)
          => link_to "Edit", '', class: 'btn btn-xs btn-warning edit-question-link', data: { question_id: @question.id }
          = link_to "Delete", @question, method: :delete, class: "btn btn-xs btn-danger"
          = form_for @question, remote: true, html: { id: "edit-question" } do |f|
            br
            .form-group
              = f.label :title, 'Title:'
              = f.text_field :title, class: "form-control"
            .form-group
              = f.label :body, 'Description:'
              = f.text_area :body, size: "60x12", class: "form-control"
            = f.submit "Save", class: "btn btn-sm btn-primary"

app/views/questions/index.html.slim
.row
  .col-md-12.text-center
    h2 Welcome to Questions & Answers!
.row
  .col-md-12.text-center
    =link_to "Ask a question", new_question_path, class: 'btn btn-success'
p  
hr
.row
  .col-md-12
    - cache collection_cache_key_for :question do
      .questions
        - @questions.each do |q|
          h3
            i> class="fa fa-question-circle"
            = link_to q.title, q
          p
            = q.body
= subscribe_to "/questions"

app/views/questions/new.html.slim
= form_for @question do |f|
  .form-group
    = f.label :title, 'Title:'
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :body, 'Description:'
    = f.text_area :body, size: "60x12", class: "form-control"
  p 
  = render 'attachments', f:f
br
br
=link_to "To question index", questions_path, class: 'btn btn-sm btn-default'

app/views/questions/show.html.slim
- cache_unless user_signed_in?, @question do
  .question
    = render @question
  .row
    .col-md-1
    .col-md-11
      em Comments:
      hr
      .q-comments data={question_id: "#{@question.id}"}
        = render 'comments/comment', commentable: @question
      .q-comments-errors
      - if can?(:create, Comment)
        = form_for [@question, Comment.new],
            html: { class: "form-inline new-question-comment" }, 
            remote: true, 
            data: { type: :json, commentable_id: @question.id } do |f|
          .form-group
            = f.label :body, 'Enter a comment', class: "sr-only"
            = f.text_field :body, class: "form-control"
          = f.submit "Send", class: "btn btn-xs btn-primary"
      
  br
  h4 Answers:
  hr
  .answers data={question_id: "#{@question.id}"}
    - if @question.answers.any? 
      = render @answers

  - if can?(:create, Answer)
    hr
    .new_answer_info
    = form_for [@question, @question.answers.build], remote: true do |f|
      .form-group
        = f.label :body, 'Your answer:'
        = f.text_area :body, size: "60x12", class: "form-control"
      p 
      = render 'attachments', f:f
  br
  br
    = link_to "To questions list", questions_path, class: "btn btn-md btn-default"

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"

app/views/questions/subscribe.js.erb
$('.subscribe-button').hide();
$('.unsubscribe-button').show();
$('.subscribed-info').show();

app/views/questions/unsubscribe.js.erb
$('.subscribed-info').hide();
$('.unsubscribe-button').hide();
$('.subscribe-button').show();

app/views/questions/update.js.erb
$('.flash-notice').html("<%= j render 'notice' %>");
$('.question').html('<%= j render @question %>');
$('#edit-question').hide();