config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  resources :questions, shallow: true, concerns: :votable do
    resources :comments, only: [:create], defaults: { commentable: 'questions' }
    member do
      patch :subscribe
      delete :unsubscribe
    end
    resources :answers, only: [:create, :destroy, :update], concerns: :votable do
      resources :comments, only: [:create], defaults: { commentable: 'answers' }
      member do
        patch 'best'
      end
    end
  end

  resources :attachments, only: [:destroy]

  root 'questions#index'
  get '/search', to: 'searches#search'
  get '/terms', to: redirect('/terms.html')
  get '/privacy', to: redirect('/privacy.html')

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, shallow: true, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, dependent: :destroy, as: :attachable, inverse_of: :attachable

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true, length: { maximum: 5000 }
  validates :question_id, presence: true
  validates :user_id, presence: true

  default_scope { order(bestflag: :desc) }
  default_scope { order(created_at: 'ASC') }

  after_create :notify_subscribers_of_question

  def set_best
    transaction do
      question.answers.update_all(bestflag: false)
      update!(bestflag: true)
    end
  end

  private

  def notify_subscribers_of_question
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_answer, only: [:destroy, :update, :best]
  before_action :find_question, only: [:create, :update, :best]

  respond_to :js

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def update
    return unless current_user.author_of?(@answer)
    @answer.update(answer_params)
    load_answers
    respond_with(@answer)
  end

  def destroy
    respond_with(@answer.destroy) if current_user.author_of?(@answer)
  end

  def best
    @answer.set_best if current_user.author_of?(@question)
    load_answers
  end

  private

  def find_question
    @question = if params[:question_id]
                  Question.find(params[:question_id])
                else
                  @answer.question
                end
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def load_answers
    @answers = @question.answers
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:index, :create]

  authorize_resource

  def index
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    respond_with(
      @answer = @question.answers.create(
        answer_params.merge(user: current_resource_owner)
      )
    )
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache_unless user_signed_in?, answer do
  div class="row answer-#{answer.id}"
    .col-md-1.answer-rating
      .answer-votes
        - if user_signed_in? && !current_user.author_of?(answer)
          div class="a-vote-button-up-#{answer.id}" style=('display:none' unless can?(:vote_up, answer))
            =>link_to('',vote_up_answer_path(answer), method: :patch, 
                     class: 'fa fa-sort-asc', 
                     id:"a-vote-up", remote: true, data: { type: :json, answer_id: answer.id })
        span class="a-rating" id="a-rating-#{answer.id}" =answer.votes_sum 

        - if user_signed_in? && !current_user.author_of?(answer)
          div class="a-cancel-vote-#{answer.id}" style=('display:none' unless can?(:cancel_vote, answer))
            =link_to('',cancel_vote_answer_path(answer), method: :delete, 
              class: 'fa fa-times', id: 'a-cancel-vote', remote: true, data: { type: :json, answer_id: answer.id })
          div class="a-vote-button-down-#{answer.id}" style=('display:none' unless can?(:vote_down, answer))
            =link_to('',vote_down_answer_path(answer), method: :patch,
                     class: 'fa fa-sort-desc',
                     id:"a-vote-down", remote: true, data: { type: :json, answer_id: answer.id })
    .col-md-1
      .best-flag
        - if answer.bestflag
          span id="best_answer" class="fa fa-check"    
        - else
          - if can?(:best, answer)
            = link_to "Best", best_answer_path(answer), method: :patch, remote: true, 
                      class: 'btn btn-xs btn-default' 
    .col-md-10.well.well-sm  
      = answer.body

      - if answer.attachments.any?
        div class="attachments-#{answer.id}" data-answer-id="#{answer.id}" 
          br
          strong
            em Attachments:
          ul
            - answer.attachments.each do |a|
              li id="file-#{a.id}"
                = link_to a.file.identifier, a.file.url
                |&nbsp;&nbsp;&nbsp;
                - if can?(:destroy, a)
                  = link_to('', a, method: :delete, id: "delete-file-#{a.id}", class: 'fa fa-trash-o btn btn-xs btn-danger', remote: true)

      - if can?(:update, answer) && can?(:destroy, answer)
        div class= "edit_answer_#{answer.id}" id="edit_answer_info"
        br
        => link_to "Edit", '', class: 'btn btn-xs btn-warning edit-answer-link', data: { answer_id: answer.id }
        = link_to "Delete", answer, method: :delete, remote: true, class: "btn btn-xs btn-danger" 
        = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          br
          .form-group
            = f.label :body, 'Your answer:'
            = f.text_area :body, size: "40x6", class: "form-control"
          = f.submit "Save", class: "btn btn-xs btn-primary"
      .row
        .col-md-1
        .col-md-11
          br
          em Comments:
          hr
          div class="a-comments-#{answer.id}" id="a-comments"
            = render 'comments/comment', commentable: answer
          div class="a-comments-errors-#{answer.id}"
          - if can?(:create, Comment)
            = form_for [answer, Comment.new], 
              html: { class: "form-inline new-answer-comment", 
                id: "new-answer-comment-#{answer.id}" }, 
                remote: true, 
                data: { type: :json, commentable_id: answer.id } do |f|
              .form-group
                = f.label :body, 'Enter a comment', class: "sr-only"
                = f.text_field :body, class: "form-control comment-body-#{answer.id}"
              = f.submit "Send", class: "btn btn-xs btn-primary"

app/views/answers/best.js.erb
$('.answers').html("<%= j render @answers %>");

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |msg| %>
    $('.new_answer_info').html('<div class="alert alert-danger"><%= j msg %></div>').show();
  <% end %>
<% else %>
  $('.new_answer_info').html('<%= j render 'notice' %>').show();
  $('.answers').append('<%= j render @answer %>');
  $('#new_answer').find('#answer_body').val('');
<% end %> 

app/views/answers/destroy.js.erb
$('.new_answer_info').html('<%= j render 'notice' %>').show();
$('.answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |msg| %>
    $('.edit_answer_<%= @answer.id%>').html('<div class="alert alert-danger"><%= j msg %></div>').delay(1000).fadeOut(400);
  <% end %>
<% else %>
  $('.new_answer_info').html('<%= j render 'notice' %>').show();
  $('.answers').html('<%= j render @answers %>'); 
<% end %> 